### ISSUE TITLE
无法控制空调

### ISSUE THREAD

**Issue by Stillrainy** [georgezhao2010/climate_ewelink#1]
可以正常添加集成，并登陆易微联账户，且正确地识别添加了空调。
![image](https://user-images.githubusercontent.com/51181403/123557290-a95cf180-d7c2-11eb-9b26-fc053edeefe1.png)
但是无法对空调进行任何控制，并且可以显示空调的运行状态但无法显示当前温度。
![image](https://user-images.githubusercontent.com/51181403/123557314-d7423600-d7c2-11eb-9f18-b1bd08d8fb29.png)

日志中出现websocket error，具体如下：
![image](https://user-images.githubusercontent.com/51181403/123557338-02c52080-d7c3-11eb-80dc-18622ec08253.png)

当前pip中websocket-client的版本为1.1.0

**Comment by georgezhao2010** [comment]
你是Hassbian的Zhizhi？如果不是的话，那么你可能和他一个问题。
易微联账号不允许多点登录，因此需要使用不同账号登录，否则HA和App之间会互相踢掉，导致websocket断线。
具体做法就是，先用一个账号绑定美居，获取空调后，分享给另一个易微联账号，然后两个账号分别给HA集成和App使用。

**Comment by georgezhao2010** [comment]
我想请问一下您HomeAssistant安装的什么版本？我看了一下，最新的websocket-client只有0.5X.X啊。

**Comment by georgezhao2010** [comment]
我去https://pypi.org/project/websocket-client下载了最新的1.1.0的代码，与最新的HomeAssistant2021.6.6中的websocket代码中的执行回调的方式比较了一下。

现有的的回调调用之前会检查回调是否是class method
```
def _callback(self, callback, *args):                                                                                                                      
        if callback:                                                                                                                                           
            try:                                                                                                                                               
                if inspect.ismethod(callback):                                                                                                                 
                    callback(*args)                                                                                                                            
                else:                                                                                                                                          
                    callback(self, *args)
```

而新的websocket这段代码变成了
```
    def _callback(self, callback, *args):
        if callback:
            try:
                callback(self, *args)
```
也就是说去掉了是否class method的检查，而我正是使用了class method作为回调，所以导致参数对不上了。

我暂时不知道他们为什么要去掉检查，也不太知道这个问题需要我去修正还是websocket去修正。

我还是建议您暂时在标准的HomeAssistant中运行。

**Comment by georgezhao2010** [comment]
Fine, I'll fix it.

**Comment by Stillrainy** [comment]
因为我的websocket-client是通过pip自行安装的，后来降级到0.57.0版本确实可以正常运行。不过还是要感谢您这么快就解决了这个问题。

**Comment by mickey50** [comment]
> Fine, I'll fix it.

可以兼容1.1.0的websocket-client了么？我的最新版还是报同样的错误。使用hassio docker 方式安装的ha

**Comment by mickey50** [comment]
> > Fine, I'll fix it.
> 
> 可以兼容1.1.0的websocket-client了么？我的最新版还是报同样的错误。使用hassio docker 方式安装的ha

可以了，还是因为多账户登陆的问题，以为退出app登录就行了，忘记了ha上还装了ewelink的插件
