### ISSUE TITLE
出现这个错误，并且无法恢复

### ISSUE THREAD

**Issue by gmugu** [georgezhao2010/climate_ewelink#3]
此错误来自自定义集成。

Logger: root
Source: custom_components/climate_ewelink/ewelinkcloud.py:61
Integration: Midea A/C via eWeLink (documentation, issues)
First occurred: 15:03:41 (1 occurrences)
Last logged: 15:03:41

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cn-api.coolkit.cn', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/climate_ewelink/statemanager.py", line 134, in run
    if self._ewelink_cloud.login():
  File "/config/custom_components/climate_ewelink/ewelinkcloud.py", line 61, in login
    r = requests.post(f"https://{SERVERS[self._country]}/api/user/login", json=payload,
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cn-api.coolkit.cn', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by georgezhao2010** [comment]
是从来就不能正常使用还是偶尔出？是启动HA就出还是使用过程中出？出问题时你的网络外网连接是否正常？

**Comment by georgezhao2010** [comment]
> 此错误来自自定义集成。
> 
> Logger: root
> Source: custom_components/climate_ewelink/ewelinkcloud.py:61
> Integration: Midea A/C via eWeLink (documentation, issues)
> First occurred: 15:03:41 (1 occurrences)
> Last logged: 15:03:41
> 
> Uncaught thread exception
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
> conn = connection.create_connection(
> File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
> for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Try again
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
> httplib_response = self._make_request(
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
> self._validate_conn(conn)
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
> conn.connect()
> File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
> conn = self._new_conn()
> File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
> raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
> resp = conn.urlopen(
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
> retries = retries.increment(
> File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cn-api.coolkit.cn', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> self.run()
> File "/config/custom_components/climate_ewelink/statemanager.py", line 134, in run
> if self._ewelink_cloud.login():
> File "/config/custom_components/climate_ewelink/ewelinkcloud.py", line 61, in login
> r = requests.post(f"https://{SERVERS[self._country]}/api/user/login", json=payload,
> File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
> return request('post', url, data=data, json=json, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
> return session.request(method=method, url=url, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cn-api.coolkit.cn', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again'))

是从来就不能正常使用还是偶尔出？是启动HA就出还是使用过程中出？出问题时你的网络外网连接是否正常？

**Comment by gmugu** [comment]
> > 此错误来自自定义集成。
> > Logger: root
> > Source: custom_components/climate_ewelink/ewelinkcloud.py:61
> > Integration: Midea A/C via eWeLink (documentation, issues)
> > First occurred: 15:03:41 (1 occurrences)
> > Last logged: 15:03:41
> > Uncaught thread exception
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
> > conn = connection.create_connection(
> > File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
> > for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> > File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
> > for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> > socket.gaierror: [Errno -3] Try again
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
> > httplib_response = self._make_request(
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
> > self._validate_conn(conn)
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
> > conn.connect()
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
> > conn = self._new_conn()
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
> > raise NewConnectionError(
> > urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
> > resp = conn.urlopen(
> > File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
> > retries = retries.increment(
> > File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
> > raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cn-api.coolkit.cn', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again'))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > self.run()
> > File "/config/custom_components/climate_ewelink/statemanager.py", line 134, in run
> > if self._ewelink_cloud.login():
> > File "/config/custom_components/climate_ewelink/ewelinkcloud.py", line 61, in login
> > r = requests.post(f"https://{SERVERS[self._country]}/api/user/login", json=payload,
> > File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
> > return request('post', url, data=data, json=json, **kwargs)
> > File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
> > return session.request(method=method, url=url, **kwargs)
> > File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
> > resp = self.send(prep, **send_kwargs)
> > File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
> > r = adapter.send(request, **kwargs)
> > File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
> > raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cn-api.coolkit.cn', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b448130>: Failed to establish a new connection: [Errno -3] Try again'))
> 
> 是从来就不能正常使用还是偶尔出？是启动HA就出还是使用过程中出？出问题时你的网络外网连接是否正常？

之前一直正常用着，就那个时候突然就挂了，然后一直这样没恢复，之后没重启，猜想重启了就会恢复了，估计是当时家里网络异常了。
中途断网可能导致这个组件出现异常且无法自动恢复，能否加个网络异常判断，不让它挂，网络连上之后就自动恢复
