### ISSUE TITLE
空调防直吹功能不可用

### ISSUE THREAD

**Issue by TrickLin** [georgezhao2010/climate_ewelink#4]
空调型号是华凌的N8HE1 按照您的帖子正常接入
但是Hass网页上 防直吹的开关是灰色的 无法点击
我看了那个帖子的回复 好像说是易微联把状态消息中的防直吹给取消了

但是通过插件-HASS(HAOS)-Homekit家庭App 是可以正常显示防直吹按钮的 而且点击后 空调也可以把挡板抬上去
不知道有没有什么曲线救国的办法呢...

**Comment by TrickLin** [comment]
补充 使用美的美居App 打开空调防直吹之后
在HASS中 空调防直吹状态显示为开 这时在HASS中操作防直吹关闭 空调放下了挡板
但是之后按钮就不可用了 重新操作防直吹开 无响应

**Comment by georgezhao2010** [comment]
我已经说过了是易微联取消了这个字段
以下是我与易微联客服的沟通结果，客服与开发的沟通截图
![inline-1277601303](https://user-images.githubusercontent.com/27534713/127216503-d9f19c12-2d12-4b75-9813-15f950249c4c.png)

**Comment by georgezhao2010** [comment]
不过我会想办法曲线救国的

**Comment by TrickLin** [comment]
谢谢！
